import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout'
import { createUser, googleLogin, logout } from '../firebase/Users/main'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RZ nextjs-temaplate </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons.icon.ico" />
      </Head>
      <div>
        Template nextjs
        <h2>Contains some packages and configs</h2>
        <ul className="list-decimal">
          <li className="">tailwindcss</li>
          <li className="">daisyUI</li>
          <li className="">prettier</li>
          <li className="">eslint</li>
          <li className="">typescript</li>
          <li className="">redux </li>
          <li className="">react-redux</li>
          <li className="">redux-toolkit</li>
          <li className="">firebase</li>
          <li className="">firebaseCRUD</li>
          <li className="">firebase-date-util</li>
        </ul>
      </div>
    </>
  )
}

export default Home
