import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout'
import { createUser, googleLogin, logout } from '../firebase/Users/main'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RZ nextjs-temaplate </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons.icon.ico" />
      </Head>
      <Layout>
        <div className="font-bold">Nueva aplicación</div>
        <div>
          <button
            onClick={() => {
              googleLogin()
            }}
          >
            Login
          </button>
          <button
            onClick={(e) => {
              e.preventDefault()
              logout()
            }}
          >
            logout
          </button>
        </div>
        <form
          onSubmit={(e) => {
            e.preventDefault()
            createUser({ name: 'User name' })
          }}
        >
          <input placeholder="Nombre" />
          <button>Submit</button>
        </form>
      </Layout>
    </div>
  )
}

export default Home
